<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TypeSafe.Sdk</RootNamespace>
    <Description>C# client for the TypeSafe API.</Description>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="TypeSafe.Sdk.Tests" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>
</Project>
